# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runze', '0002_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='ordem',
            field=models.CharField(default='First', max_length=20),
            preserve_default=False,
        ),
    ]
