# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runze', '0003_carousel_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(upload_to='destaque/')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='tipo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carousel',
            name='imagem',
            field=models.ImageField(upload_to='carousel/'),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runze.Menu'),
        ),
    ]
