# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runze', '0006_menu_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='menu/'),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='imagem',
            field=models.ImageField(upload_to='conteudo/'),
        ),
    ]
