# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runze', '0007_auto_20170712_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='imagem',
            field=models.ImageField(blank=True, default='', upload_to='menu/'),
            preserve_default=False,
        ),
    ]
