# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runze', '0008_auto_20170712_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.CharField(max_length=200, verbose_name='E-mail')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('texto', models.TextField(verbose_name='Mensagem')),
            ],
        ),
    ]
